### ISSUE TITLE
(Request) Icon size

### ISSUE THREAD

**Issue by toofewacres** [amaximus/garbage-collection-card#1]
I installed your card. Works great. Icon changed to red like it is supposed to a day before which is just what I want.

I have a Feature request of being able to increase the Icon size, The entity-button card allows you to add icon_height: 40px #or what ever height you want. In my layout I would like to have a bigger icon for a little more emphasis on the upcoming garbage day.

Thanks for creating this card.

**Comment by amaximus** [comment]
Added support for icon size via configuration parameter.

It might take a couple of hours for HACS to pick it up and make it available.

**Comment by toofewacres** [comment]
Great. I will try it out once HACS updates and I get a few minutes.

Thank you. 

⁣Sent from TypeApp ​

**Comment by SeLLeRoNe** [comment]
Would be possible to also have an icon color? 

Thanks! :)

**Comment by toofewacres** [comment]
Icon size works perfectly. Thank you.

**Comment by amaximus** [comment]
Added icon color support.

**Comment by SeLLeRoNe** [comment]
Unfortunately the icon_color directive doesn't seems to be working to me.

This is the code I am using:
```
          - type: custom:garbage-collection-card
            entity: sensor.plastic
            icon_color: yellow
```

**Comment by amaximus** [comment]
Please try to clean the browser caches then shift-reload.

**Comment by SeLLeRoNe** [comment]
Ok it does work, but it doesn't work on the "due" icons which remains red, that's why I didn't notice a difference :)

Would be possible to have a "normal state" icon color and "due state" icon color?

This way we can define ourself what is the color for when it is due which better match the them :)

I will opena  new FR for another idea I have in mind without having everything on this icon related issue.

Thanks
