### ISSUE TITLE
Don't take custom "verbose output" into account without verbose

### ISSUE THREAD

**Issue by poofyteddy** [amaximus/garbage-collection-card#16]
Hi,
Thank's for the card :)
I'm a french user, and i have set the verbose output of the garbage in french.
Your card seam to build it's own text, and it look like this isn't editable.
in order to have my text in french, i can enable verbose output on the entity, but that force the date on, something i don't want to see (bi-weekely, so no need there)

Could you add a way to ether:
- grab verbose output data from the integration, and use that for the card output
- allow removing date when verbose is enable on the integration
- allow custom text for the card

**Comment by amaximus** [comment]
Hi,
there was a bug in what was displayed when verbose_state=Yes. This has been fixed in the latest version of the card. In such case the text from verbose_format of the custom component is displayed.

Please make sure you are using the latest vesion of the card, verbose_state=yes and you set a custom text in verbose_format.

Please get back to me with results.

**Comment by poofyteddy** [comment]
so it look like i'm running on the latest version, i try both with the master branch, and the 1.0.0 release. same output.
But i'm not sure i explain clearely enough what my issue was.
![image](https://user-images.githubusercontent.com/33599733/71555967-72bde380-2a32-11ea-80e6-191a88d99cd6.png)
in this picture you can see the top the card without verbose and under it the card with verbose.
Both have the same 'verbose_format' set with french instead of English template. Both card use the `hide_date: true`

My issue is that without verbose (top card) your card don't fetch the verbose_format set up in the entity. But with verbose (bottom card) your card can't remove the date.

This is why i'm asking for one of the above list :)

**Comment by amaximus** [comment]
Ok, I got it now.
So when you don't use verbose_state (or it's set to no) there is no point on relying on/using the verbose_format.
When you use verbose_state=yes, the hide_date and hide_days are discarded and the text defined by verbose_format ia displayed. This is explicitely mentioned in the Readme.

It is not clear for me whether you define a custom verbose_format or you are using the default text (localized to French).

**Comment by poofyteddy** [comment]
lack of information from me once again.
There is no translation set up, the output of the second card is a custom verbose_format.
Reading the doc before opening this issue/request, i saw that hide_date would not work with verbose, but there lies my issue.
Without verbose and custom verbose_format, your card is English only, and with verbose i cannot remove the date.
This is why i was looking for a way to customize the output of the card, either by it using the already set-up custom verbose_format, or by adding some setting :)

**Comment by amaximus** [comment]
With verbose_state=true you may display whatever - even generated - string if you set the verbose_format for the sensor.

Once you don't use verbose_state (or it is set to either no or false) the card will display fixed string in English. There is no real support for other languages in HA or the custom card, however following lines in the card's code try to use some localization for days:
```
            ${hdays === false ? " " + `${this._label('ui.components.relative_time.future.In', 'in')}` +
                                " " + `${attribute.days}` + " " + `${this._label('ui.duration.days', 'days')}` : '' }
```
Since expressing the date in different languages are very different, there is nothing similar to the above for date,

So I'd recommend using verbose_state=true and and setting some verbose_format.

**Comment by poofyteddy** [comment]
Sorry for the delay, rush at job during the holiday, so i took my break after it.
Your proposal is actually what i do in my second card, a verbose_state=true with some verbose_format.
This is actually why i was asking to add a setting to hide the date from the verbose_state.
i don't want the date, i only want to see the "in X day" verbose_state, but as stated in the doc this isn't actually possible.

If you don't find that usefull, it's ok to let this issue close ;)

**Comment by amaximus** [comment]
In verbose_state=yes the custom component provides the text output defined by verbose_format, while the verbose_format (if defined) is up to the user to build the string. The custom card only displays the defined (or default) string, being the state of the sensor.
