### ISSUE TITLE
[BUG] Language of Browser Prefered over Account Language

### ISSUE THREAD

**Issue by JonahKr** [amaximus/garbage-collection-card#57]
**Describe the bug**
I had my Browser (Chrome) language changed to german on accident which lead the card to choose the german wording altough my hass user has en-GB set as a language.
I don't know if this is intentional or more of a question of which to prioritize.

**To Reproduce**
Change Browser to different language then your Homeassistant User.

**Expected behavior**
The Card Using the Homeassistant language.

**Environment (please complete the following information):**
 - Garbage Collection Card version: 1.15.2
 - Browser: chrome
 - Browser language: german

Maybe if i have time i can create a PR if i have enough time this week...

**Comment by amaximus** [comment]
Using browser language for displaying the card was intentional, however I admit that Home Assistant account language preference could have been taken into consideration.

Anyway, newest release 1.16.1 addresses this issue, adding a new configuration parameter.
Please update your card and get back to me with results.

**Comment by JonahKr** [comment]
I tried it and it works perfectly. Thank you very much 👍
