### ISSUE TITLE
Lovelace black screen after adding 'custom:garbage-collection-card'

### ISSUE THREAD

**Issue by TheIronRock95** [amaximus/garbage-collection-card#66]
**Describe the bug**
Hello,

I am trying to get the custom-card "garbage-collection-card" in lovelace only when I add the card I get a black empty dashboard. I have installed the garbage-collection-card through HACS and added the Resources under lovelace/resource

```
/hacsfiles/garbage-collection-card/garbage-collection-card.js
```

The lovelace dashboard config for the garbage card is:

```
      - type: 'custom:garbage-collection-card'
        entity: sensor.afvalinfo_pbd
        icon_size: 35px
        icon_color: green
```
Another custom card 'custom: simple-thermostat' does work fine in the dashboard.

To answer the questions for: [Community home assistant ]( https://community.home-assistant.io/t/lovelace-black-screen-after-adding-custom-garbage-collection-card/261638/2?u=theironrock95)

sensor.afvalinfo_pbd is an attributes under Developer Tool: 
![image](https://user-images.githubusercontent.com/58424695/103352605-edd33300-4aa6-11eb-851a-851b4cae7f00.png)

The browser console is giving me the following error: 
![image](https://user-images.githubusercontent.com/58424695/103352640-05aab700-4aa7-11eb-9a1d-51f8108d312a.png)

The black and empty dashboard: 
![image](https://user-images.githubusercontent.com/58424695/103352753-6803b780-4aa7-11eb-93ec-4709b36a87cf.png)

**Comment by amaximus** [comment]
Please note that the garbage-collection-card was written to support the custom Garbage Collection integration [1], thus expecting state value and attributes as provided by [1].
According to your screenshot, the sensor.afvalinfo_pbd (and the similar ones) is not provided by the custom Garbage Collection integration [1], your sensor has different state value and attributes, that's why it doesn't work. I will still issue a fix to avoid the above error.
The card can work with sensor of other integrations as long as the state value and attributes are as expected by [1].

[1] https://github.com/bruxy70/Garbage-Collection/

**Comment by wouterdamman** [comment]
Ah okey, will check it out!! The black screen is fixed so thanks 🙃
