### ISSUE TITLE
[FeatureRequest] display title & details inline

### ISSUE THREAD

**Issue by ljagiela** [amaximus/garbage-collection-card#93]
Is there a chance that you could add a configuration parameter to display title & details inline?

**Comment by amaximus** [comment]
You may use custom button-card [1] to build an inline-type button-card. It provides a great flexibility (that's why I'm not creating custom cards for my newer integrations).
See an example at one of my other github repositories [2].

[1] https://github.com/custom-cards/button-card
[2] https://github.com/amaximus/met_alerts_hu
